name = "kv-rest-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Environment variables can be added here

[[kv_namespaces]]
binding = "KV"
id = "04d0e33bf17247628c22f96b93bc0362"

# Development environment configuration
[env.dev]
name = "kv-rest-api-dev"

# Production environment configuration
[env.production]
name = "kv-rest-api-prod"